version: 2.07.{build}

image:
- Visual Studio 2017
- Ubuntu

configuration: Release
platform: x64
shallow_clone: true

test: off

for:
- matrix:
    except:
    - image: Ubuntu
  build:
    project: TheDarkMod.sln
    parallel: true
    verbosity: minimal
  after_build:
  - cmd: >-
      7z a -t7z TheDarkMod.7z ..\darkmod\*.exe
      
      7z a -t7z TheDarkMod.7z ..\darkmod\*.dll

  artifacts:
  - path: TheDarkMod.7z
    name: TheDarkMod

- matrix:
    only:
    - image: Ubuntu

  install:
  - sh: >-
      sudo apt-get update
      
      sudo apt-get -y install scons m4 subversion mesa-common-dev libxxf86vm-dev libopenal-dev libxext-dev

  build_script:
  - sh: >-
      mkdir build
      
      scons BUILD="release" TARGET_ARCH="x64" -j4 build

  after_build:
  - sh: >-
      tar -cSvf thedarkmod.tar thedarkmod.x64 *.so
      
      bzip2 thedarkmod.tar

  artifacts:
  - path: thedarkmod.tar.bz2
    name: TheDarkModLinux
