version: 2.07.{build}

image:
- Visual Studio 2017
- Ubuntu

configuration:
- release
- debug
platform:
- Win32
- x64
shallow_clone: true

test: off

for:
- matrix:
    except:
    - image: Ubuntu
  build:
    project: TheDarkMod.sln
    parallel: true
    verbosity: minimal
  after_build:
  - cmd: >-
      7z a -t7z TheDarkMod.7z ..\darkmod\*.exe
      
      7z a -t7z TheDarkMod.7z ..\darkmod\*.dll

  artifacts:
  - path: TheDarkMod.7z
    name: TheDarkMod

- matrix:
    only:
    - image: Ubuntu

  install:
  - sh: >-
      sudo apt-get update
      
      sudo apt-get -y install scons m4 subversion mesa-common-dev libxxf86vm-dev libopenal-dev libxext-dev
      
      if [ $PLATFORM = "Win32" ]; then
        
          export PLATFORM="x86"
        
      fi

  build_script:
  - sh: >-
      mkdir build
      
      scons BUILD="${CONFIGURATION}" TARGET_ARCH="${PLATFORM}" -j4

  after_build:
  - sh: >-
      tar -cSvf thedarkmod.tar "thedarkmod.${PLATFORM}" *.so

      bzip2 thedarkmod.tar

  artifacts:
  - path: thedarkmod.tar.bz2
    name: TheDarkModLinux
