version: 2.07.{build}

image:
- Visual Studio 2017
- Ubuntu

configuration:
- release

platform:
- x64

shallow_clone: true

test: off

for:
- matrix:
    except:
    - image: Ubuntu
  build:
    project: TheDarkMod.sln
    parallel: true
    verbosity: minimal
  after_build:
  - cmd: >-
      7z a -t7z TheDarkMod.7z ..\darkmod\*.exe
      
      7z a -t7z TheDarkMod.7z ..\darkmod\*.dll

  artifacts:
  - path: TheDarkMod.7z
    name: TheDarkMod

- matrix:
    only:
    - image: Ubuntu

  install:
  - sh: >-
      sudo apt-get update
      
      sudo apt-get -y install scons m4 subversion mesa-common-dev libxxf86vm-dev libopenal-dev libxext-dev
      
      if [ $PLATFORM = "Win32" ]; then
      
          sudo apt-get -y install g++-multilib libx11-dev:i386 libxxf86vm-dev:i386 libopenal-dev:i386 libxext-dev:i386
        
          export PLATFORM="x86"
        
      fi

  build_script:
  - sh: >-
      mkdir build
      
      scons BUILD="${CONFIGURATION}" TARGET_ARCH="${PLATFORM}" -j4

  after_build:
  - sh: >-
      tar -cSvf thedarkmod.tar "thedarkmod.${PLATFORM}" *.so

      bzip2 thedarkmod.tar
      
  before_test:
  - sh: >-
      mkdir -p script
      
      touch script/tdm_defs.script
      
      touch script/tdm_main.script
      
      mkdir -p materials
      
      touch materials/lights.mtr
      
      touch materials/tdm_ai_steambots.mtr
      
      touch materials/tdm_light_textures.mtr
      
      touch materials/tdm_lights_d3_leftover.mtr
      
      echo "_default {{map _default}}" > materials/tdm_internal_engine.mtr
      
      echo "unbindall" > default.cfg
      
  test_script:
  - sh: >-
      ./thedarkmod.${PLATFORM} +set com_skipRenderer 1 +set com_runTests 1

  artifacts:
  - path: thedarkmod.tar.bz2
    name: TheDarkModLinux
