version: trunk{build}

shallow_clone: true

# configure matrix of builds
image:
- Visual Studio 2022
- Ubuntu1804
platform:
- 64
- 32
configuration:
- msvc_main     # build Debug + Release on vcxproj
- msvc_extra    # build extra configurations on vcxproj
- cmake         # build using CMake
environment:
  matrix:
    - thirdparty: artefacts     # use artefacts from SVN (conan-less)
    - thirdparty: rebuild       # regenerate artefacts using conan then use them
    - thirdparty: conan         # conan build

matrix:
  exclude:
    - configuration: msvc_main
      image: Ubuntu1804
    - configuration: msvc_extra
      image: Ubuntu1804
    - configuration: msvc_main
      thirdparty: conan
    - configuration: msvc_extra
      thirdparty: conan
    - configuration: msvc_extra
      thirdparty: rebuild

# need conan for anything except conan-less build
for:
- matrix:
    except:
    - thirdparty: artefacts
  install:
    - pip install conan

# build scripts
for:
- matrix:
    only:
    - image: Visual Studio 2022
      configuration: msvc_main
      thirdparty: artefacts
  build_script:
    - cmd: |
      cd CiScripts
      build_msvc_main.cmd ${PLATFORM}

- matrix:
    only:
    - image: Visual Studio 2022
      configuration: msvc_extra
      thirdparty: artefacts
  build_script:
    - cmd: |
      cd CiScripts
      build_msvc_extra.cmd ${PLATFORM}

- matrix:
    only:
    - image: Visual Studio 2022
      configuration: msvc_main
      thirdparty: rebuild
  build_script:
    - cmd: |
      cd CiScripts
      python conan_rebuild_artefacts_ci.py force
      build_msvc_extra.cmd ${PLATFORM}

- matrix:
    only:
      configuration: cmake
      thirdparty: artefacts
  build_script:
    - sh: |
      cd CiScripts
      python ./build_cmake.py ${PLATFORM}

- matrix:
    only:
      configuration: cmake
      thirdparty: rebuild
  build_script:
    - cmd: |
      cd CiScripts
      python ./conan_rebuild_artefacts_ci.py force
      python ./build_cmake.py ${PLATFORM}

- matrix:
    only:
    - configuration: cmake
      thirdparty: conan
  build_script:
    - cmd: |
      cd CiScripts
      python conan_build.py ${PLATFORM}
