set(PUGIXML_INCLUDE_DIRS "${PROJECT_SOURCE_DIR}/ThirdParty/artefacts/pugixml/include")
set(PUGIXML_LIBRARY_DIR "${PROJECT_SOURCE_DIR}/ThirdParty/artefacts/pugixml/lib/lnx64_s_gcc5_rel_stdcpp")
set(PUGIXML_LIBRARIES "${PUGIXML_LIBRARY_DIR}/libpugixml.a")
set(PUGIXML_LIBRARY_D_DIR "${PROJECT_SOURCE_DIR}/ThirdParty/artefacts/pugixml/lib/lnx64_s_gcc5_rel_stdcpp")
set(PUGIXML_LIBRARIES_D "${PUGIXML_LIBRARY_D_DIR}/libpugixml.a")
